"""baseline: airports, flight_edges, danger_zones

Revision ID: b8484757374c
Revises: 
Create Date: 2026-07-22 16:23:02.490774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'b8484757374c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('iata_code', sa.String(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('risk_description', sa.String(), nullable=True),
    sa.Column('severity_index', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_airports_location', 'airports', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_airports_iata_code'), 'airports', ['iata_code'], unique=True)
    op.create_index(op.f('ix_airports_id'), 'airports', ['id'], unique=False)
    op.create_geospatial_table('danger_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_event', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=True),
    sa.Column('boundary', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_danger_zones_boundary', 'danger_zones', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_danger_zones_id'), 'danger_zones', ['id'], unique=False)
    op.create_table('flight_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_iata', sa.String(), nullable=False),
    sa.Column('dest_iata', sa.String(), nullable=False),
    sa.Column('base_distance_km', sa.Float(), nullable=False),
    sa.Column('route_risk_modifier', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_edges_id'), 'flight_edges', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_edges_id'), table_name='flight_edges')
    op.drop_table('flight_edges')
    op.drop_index(op.f('ix_danger_zones_id'), table_name='danger_zones')
    op.drop_geospatial_index('idx_danger_zones_boundary', table_name='danger_zones', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_table('danger_zones')
    op.drop_index(op.f('ix_airports_id'), table_name='airports')
    op.drop_index(op.f('ix_airports_iata_code'), table_name='airports')
    op.drop_geospatial_index('idx_airports_location', table_name='airports', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('airports')
    # ### end Alembic commands ###
