"""integrity constraints and zone lifecycle

Autogenerated draft, then hand-corrected — two things autogenerate got wrong:
  1. VARCHAR -> enum conversion: the enum type must be CREATEd first, and
     Postgres needs an explicit USING cast to convert existing values.
  2. Foreign keys were created with name=None: Postgres would auto-name
     them, and downgrade()'s drop_constraint(None) would crash. Constraints
     get explicit names so the migration is reversible.

Revision ID: e1fbdf76766d
Revises: b8484757374c
Create Date: 2026-07-22 16:24:29.276041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fbdf76766d'
down_revision: Union[str, Sequence[str], None] = 'b8484757374c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

airport_risk_level = sa.Enum('Low', 'Medium', 'High', name='airport_risk_level')


def upgrade() -> None:
    """Upgrade schema."""
    # -- airports.risk_level: free text -> native enum ------------------------
    airport_risk_level.create(op.get_bind(), checkfirst=True)
    op.execute(
        "ALTER TABLE airports ALTER COLUMN risk_level "
        "TYPE airport_risk_level USING risk_level::airport_risk_level"
    )

    # -- danger_zones: identity + lifecycle ----------------------------------
    # NOT NULL is safe here because the table is empty at this point in
    # history; on a populated table the pattern is: add nullable, backfill,
    # then ALTER ... SET NOT NULL.
    op.add_column('danger_zones', sa.Column('external_id', sa.String(), nullable=False))
    op.add_column('danger_zones', sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('danger_zones', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('danger_zones', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_danger_zones_external_id'), 'danger_zones', ['external_id'], unique=True)

    # -- flight_edges: referential integrity ---------------------------------
    op.create_unique_constraint('uq_flight_edges_source_dest', 'flight_edges', ['source_iata', 'dest_iata'])
    op.create_foreign_key(
        'fk_flight_edges_dest_iata', 'flight_edges', 'airports',
        ['dest_iata'], ['iata_code'], ondelete='CASCADE',
    )
    op.create_foreign_key(
        'fk_flight_edges_source_iata', 'flight_edges', 'airports',
        ['source_iata'], ['iata_code'], ondelete='CASCADE',
    )
    op.drop_column('flight_edges', 'route_risk_modifier')


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column('flight_edges', sa.Column('route_risk_modifier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint('fk_flight_edges_source_iata', 'flight_edges', type_='foreignkey')
    op.drop_constraint('fk_flight_edges_dest_iata', 'flight_edges', type_='foreignkey')
    op.drop_constraint('uq_flight_edges_source_dest', 'flight_edges', type_='unique')
    op.drop_index(op.f('ix_danger_zones_external_id'), table_name='danger_zones')
    op.drop_column('danger_zones', 'is_active')
    op.drop_column('danger_zones', 'expires_at')
    op.drop_column('danger_zones', 'starts_at')
    op.drop_column('danger_zones', 'external_id')
    op.execute(
        "ALTER TABLE airports ALTER COLUMN risk_level "
        "TYPE VARCHAR USING risk_level::text"
    )
    airport_risk_level.drop(op.get_bind(), checkfirst=True)
